service: get-started-sls

provider:
  name: aws
  runtime: python3.8
  stage: ${env:stage}

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-offline

package:
  exclude:
    - .env

functions:
  getValueById:
    handler: handler.getValueById
    events:
      - http:
          path: value/{id}
          method: get

  getValues:
    handler: handler.getValues
    events:
      - http:
          path: value
          method: get
