service: get-started-sls

provider:
  name: aws
  runtime: python3.8
  stage: ${env:stage}

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-offline

package:
  exclude:
    - .env

functions:
  values:
    handler: handler.getValues
    events:
      - http:
          path: value
          method: get
