version: 2.1

executors:
  base-sls:
    docker:
      - image: davidwfs/base-sls:latest
    working_directory: ~/app

jobs:
  credential:
    executor: base-sls
    steps:
      - run:
          name: AWS credentials file
          working_directory: /
          command: |
            mkdir ~/.aws
            touch ~/.aws/credentials
            chmod 600 ~/.aws/credentials
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
      - persist_to_workspace:
          root: ~/.aws
          paths:
            - credentials

  deploy_to_prod:
    executor: base-sls
    steps:
      - checkout
      - attach_workspace:
          at: ~/.aws
      - run:
          name: Deploying
          command: |
            npm install -g serverless
            npm run deploy:prod

  deploy_to_dev:
    executor: base-sls
    steps:
      - checkout
      - attach_workspace:
          at: ~/.aws
      - run:
          name: Deploying
          command: |
            npm install -g serverless
            npm run deploy:dev

workflows:
  version: 2
  deploy:
    jobs:
      - credential:
          filters:
            branches:
              only:
                - master
                - developer
      - deploy_to_prod:
          requires:
            - credential
          filters:
            branches:
              only:
                - master
      - deploy_to_dev:
          requires:
            - credential
          filters:
            branches:
              only:
                - developer
